baseURL = 'https://mmatokovic.dev/'
languageCode = 'hr'
title = 'mmatokovic'
defaultContentLanguage = 'hr'
theme = 'sleeve'
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[params]
  description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum ligula a mauris laoreet, interdum volutpat magna sollicitudin."
  alpine = true
  turbo = false
  [params.author]
    name = "mmatokovic"
    email = 'mislav.mat@hotmail.com'
    github = ''
    linkedin = ''
  [params.gallery]
    shuffle     = false
    reverse     = true
    enable_exif = false

[pagination]
  pagerSize = 10

[taxonomies]
  tag = 'tags'
  series = 'series'
  genre = 'genres'

[languages]
  [languages.hr]
    languageCode = 'hr'
    languageName = 'Hrvatski'
    contentDir = 'content/hr'
    weight = 1
    [languages.hr.menus]
      [[languages.hr.menus.main]]
        name = 'Početna'
        pageRef = '/'
        identifier = 'pocetna'
        weight = 10
      [[languages.hr.menus.main]]
        name = 'Articles'
        pageRef = '/posts'
        identifier = 'posts'
        weight = 20
      [[languages.hr.menus.main]]
        name = 'Kontaktiraj me'
        pageRef = '/contact'
        identifier = 'kontakt'
        weight = 40
      [[languages.hr.menus.main]]
        name = 'O meni'
        pageRef = '/about'
        identifier = 'o-meni'
        weight = 50
      [[languages.hr.menus.main]]
        name = 'Topics'
        pageRef = '/tags'
        identifier = 'oznake'
        weight = 70
      [[languages.hr.menus.main]]
        name = 'My Library'
        pageRef = '/books'
        identifier = 'books'
        weight = 60
  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    contentDir = 'content/en'
    weight = 2

[frontmatter]
  date = ['date', 'publishDate', 'pubdate', 'lastmod', 'modified']
  expiryDate = ['expiryDate', 'unpublishdate']
  lastmod = [':git', 'lastmod', 'modified', 'date', 'publishDate', 'pubdate']
  publishDate = ['publishDate', 'pubdate', 'date']

[module]
  [module.hugoVersion]
    extended = true
    min = "0.135.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "data"
    target = "data"
  [[module.mounts]]
    source       = "hugo_stats.json"
    target       = "assets/notwatching/hugo_stats.json"
    disableWatch = true
  [[module.mounts]]
    source = "node_modules/alpinejs/dist"
    target = "assets/js/libs/alpinejs"
  [[module.mounts]]
    source = "node_modules/alpine-turbo-drive-adapter/dist"
    target = "assets/js/libs/alpinejs-turbolinks"
  [[module.mounts]]
    source = "node_modules/@hotwired/turbo/dist"
    target = "assets/js/libs/turbo"

[build.buildStats]
  enable = true
[[build.cachebusters]]
  source = "assets/notwatching/hugo_stats\\.json"
  target = "css"
[[build.cachebusters]]
  source = "(postcss|tailwind)\\.config\\.js"
  target = "css"
[[build.cachebusters]]
  source = 'layouts/.*'
  target = 'css'

# To apply attributes to a [standalone image element](https://gohugo.io/content-management/markdown-attributes/#standalone-images), you must disable the default wrapping behavior:
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false