services:
  db:
    image: postgres
    restart: always
    volumes: 
      - ./_pgdata:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres