baseURL = 'https://mmatokovic.dev/'
languageCode = 'hr'
title = 'mmatokovic'
defaultContentLanguage = 'hr'
theme = "sleeve"
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[params]
  description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum ligula a mauris laoreet, interdum volutpat magna sollicitudin."
  [params.author]
    name = "mmatokovic"
    email = 'mislav.mat@hotmail.com'
  # For image jslibs/gallery
  [params.gallery]
    shuffle     = false
    reverse     = true
    enable_exif = false

[pagination]
  pagerSize = 10

[languages]
  [languages.hr]
    languageCode = 'hr'
    languageName = 'Hrvatski'
    contentDir = 'content/hr'
    weight = 1
    [languages.hr.menus]
      [[languages.hr.menus.main]]
        name = 'Početna'
        pageRef = '/'
        identifier = 'home'
        weight = 10
      [[languages.hr.menus.main]]
        name = 'Posts'
        pageRef = '/posts'
        identifier = 'blog'
        weight = 20
      [[languages.hr.menus.main]]
        name = 'Projekti'
        pageRef = '/projects'
        identifier = 'projects'
        weight = 30
  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    contentDir = 'content/en'
    weight = 2
    [languages.en.menus]
      [[languages.en.menus.main]]
        name = 'Projects'
        pageRef = '/projects'
        identifier = 'projects'
        weight = 10

[frontmatter]
  date = ['date', 'publishDate', 'pubdate', 'lastmod', 'modified']
  expiryDate = ['expiryDate', 'unpublishdate']
  lastmod = [':git', 'lastmod', 'modified', 'date', 'publishDate', 'pubdate']
  publishDate = ['publishDate', 'pubdate', 'date']

[module]
    [module.hugoVersion]
        min = "0.135.0"
    [[module.mounts]]
        source = "assets"
        target = "assets"
    [[module.mounts]]
        source = "layouts"
        target = "layouts"
    [[module.mounts]]
      source = "data"
      target = "data"
    [[module.mounts]]
        source       = "hugo_stats.json"
        target       = "assets/notwatching/hugo_stats.json"
        disableWatch = true
    [[module.mounts]]
      source = "node_modules/alpinejs/dist"
      target = "assets/js/lib/alpinejs"
    [[module.mounts]]
      source = "node_modules/alpine-turbo-drive-adapter/dist"
      target = "assets/js/lib/alpinejs-turbolinks"
    [[module.mounts]]
      source = "node_modules/@hotwired/turbo/dist"
      target = "assets/js/lib/turbo"

[build.buildStats]
    enable = true
[[build.cachebusters]]
    source = "assets/notwatching/hugo_stats\\.json"
    target = "css"
[[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
[[build.cachebusters]]
    source = 'layouts/.*'
    target = 'css'