baseURL = 'https://misli.mmatokovic.dev/'
languageCode = 'hr'
title = 'Misli'
defaultContentLanguage = 'hr'
theme = 'sleeve'
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[params]
  description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum ligula a mauris laoreet, interdum volutpat magna sollicitudin."
  alpine = true
  turbo = true
  [params.author]
    name = "mmatokovic"
    email = 'me@mmatokovic.dev'
    github = ''
    linkedin = ''
  [params.gallerydeluxe]
    shuffle     = false
    reverse     = true
    enable_exif = false

[pagination]
  pagerSize = 9

[taxonomies]
  tag = 'tags'
  series = 'series'
  genre = 'genres'

[languages]
  [languages.hr]
    languageCode = 'hr'
    languageName = 'Hrvatski'
    contentDir = 'content/hr'
    weight = 1
    [languages.hr.menus]
      [[languages.hr.menus.main]]
        name = 'Početna'
        pageRef = '/'
        weight = 10
      [[languages.hr.menus.main]]
        name = 'Članci'
        pageRef = '/posts'
        weight = 20
      [[languages.hr.menus.main]]
        name = 'Kontaktiraj me'
        pageRef = '/contact'
        weight = 40
      [[languages.hr.menus.main]]
        name = 'O meni'
        pageRef = '/about'
        weight = 50
      [[languages.hr.menus.main]]
        name = 'Teme'
        pageRef = '/tags'
        weight = 70
  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    contentDir = 'content/en'
    weight = 2
    [languages.en.menus]
      [[languages.en.menus.main]]
        name = 'Početna'
        pageRef = '/'
        weight = 10
      [[languages.en.menus.main]]
        name = 'Articles'
        pageRef = '/posts'
        weight = 20
      [[languages.en.menus.main]]
        name = 'Contact Me'
        pageRef = '/contact'
        weight = 40
      [[languages.en.menus.main]]
        name = 'About Me'
        pageRef = '/about'
        weight = 50
      [[languages.en.menus.main]]
        name = 'Topics'
        pageRef = '/tags'
        weight = 70

[frontmatter]
  date = ['date', 'publishDate', 'pubdate', 'lastmod', 'modified']
  expiryDate = ['expiryDate', 'unpublishdate']
  lastmod = [':git', 'lastmod', 'modified', 'date', 'publishDate', 'pubdate']
  publishDate = ['publishDate', 'pubdate', 'date']

[module]
  [module.hugoVersion]
    extended = true
    min = "0.145.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "data"
    target = "data"
  [[module.mounts]]
    source       = "hugo_stats.json"
    target       = "assets/notwatching/hugo_stats.json"
    disableWatch = true
  [[module.mounts]]
    source = "node_modules/alpinejs/dist"
    target = "assets/js/libs/alpinejs"
  [[module.mounts]]
    source = "node_modules/alpine-turbo-drive-adapter/dist"
    target = "assets/js/libs/alpinejs-turbolinks"
  [[module.mounts]]
    source = "node_modules/@hotwired/turbo/dist"
    target = "assets/js/libs/turbo"

[build.buildStats]
  enable = true
[[build.cachebusters]]
  source = "assets/notwatching/hugo_stats\\.json"
  target = "css"
[[build.cachebusters]]
  source = "(postcss|tailwind)\\.config\\.js"
  target = "css"
[[build.cachebusters]]
  source = 'layouts/.*'
  target = 'css'

# Set markup.goldmark.parser.wrapStandAloneImageWithinParagraph = false so standalone images will not be wrapped in <p>>/p> tags. Also set block = true to support attributes on block elements:
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Allow HTML in md files
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true